name: Build Hugo and Deploy

on:
  push:
    branches:
      - main
#  schedule:
#    - cron: 0 16 * * *
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: hugo --gc --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: kexima/kexima.github.io
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
          allow_empty_commit: true
          # commit_message: ${{ GitHub.event.head_commit.message }}
          full_commit_message: ${{ github.event.head_commit.message }}
          cname: www.kexima.com
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

#       - name: Upload to Tencent COS
#         uses: zkqiang/tencent-cos-action@v0.1.0
#         with:
#           args: upload -rsf --delete ./public/ / 
#           secret_id: ${{ secrets.SECRET_COS_ID }}
#           secret_key: ${{ secrets.SECRET_COS_KEY }}
#           bucket: ${{ secrets.COS_CN_BUCKET }}
#           region: ap-shanghai
# 
#       - name: Tencent CDN Purge
#         uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
#         env:
#           SECRET_ID: ${{ secrets.SECRET_COS_ID }}
#           SECRET_KEY: ${{ secrets.SECRET_COS_KEY }}
#           PATHS: "https://kexima.com/,https://www.kexima.com/"
#           FLUSH_TYPE: "delete" # optional
# 
#       - name: Deploy to Aliyun OSS
#         uses: fangbinwei/aliyun-oss-website-action@v1
#         with:
#           accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
#           accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
#           bucket: kexima
#           endpoint: oss-cn-shanghai.aliyuncs.com
#           folder: public
#           # exclude: |
#           #   tmp.txt